# .github/workflows/backend-deploy.yml
name: Deploy Backend Services

on:
  push:
    branches: [ main ]
    paths:
      - 'flask-rag/**'
      - 'node-backend/**'
      - 'ollama-server/**'
      - 'terraform/**'

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        
      - name: Auth GCP
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          
      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        
      - name: Terraform Init
        run: |
          cd terraform
          terraform init
          
      - name: Terraform Plan
        run: |
          cd terraform
          terraform plan
          
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: |
          cd terraform
          terraform apply -auto-approve

  build-and-push:
    needs: terraform
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [flask-rag, node-backend, ollama-server]
    steps:
      - uses: actions/checkout@v2
      
      - name: Auth GCP
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          
      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        
      - name: Configure Docker
        run: gcloud auth configure-docker
        
      - name: Build and Push
        run: |
          cd ${{ matrix.service }}
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ matrix.service }}:${{ github.sha }} .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ matrix.service }}:${{ github.sha }}

