# .github/workflows/frontend-deploy.yml
name: Deploy Frontend

on:
  push:
    branches: [ main ]
    paths:
      - 'quasar-frontend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install Dependencies
        run: |
          cd quasar-frontend
          npm install
          
      - name: Build
        run: |
          cd quasar-frontend
          npm run build
          
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: ${{ secrets.GCP_PROJECT_ID }}
          channelId: live

