name: Deploy Cloud Functions

on:
  push:
    branches:
      - main
    paths:
      - 'event-driven-functions/**'
      - 'terraform/modules/functions/**'
      - '.github/workflows/functions-deploy.yml'

jobs:
  deploy-functions:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: 'event-driven-functions/requirements.txt'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      # Validate requirements.txt
      - name: Test pip installation
        run: |
          cd event-driven-functions
          pip install -r requirements.txt

      # Deploy using Terraform instead of gcloud
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan -var-file=environments/dev.tfvars -target=module.functions
        
      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -var-file=environments/dev.tfvars -target=module.functions -auto-approve
        
      # Test the deployed function by uploading a test PDF if available
      - name: Test function (if test file exists)
        if: ${{ success() && hashFiles('event-driven-functions/test.pdf') != '' }}
        run: |
          # Get the bucket name from terraform output
          BUCKET_NAME=$(cd terraform && terraform output -raw pdf_upload_bucket)
          # Upload test PDF to trigger the function
          gcloud storage cp event-driven-functions/test.pdf gs://${BUCKET_NAME}/pdfs/test-$(date +%s).pdf
          echo "Test PDF uploaded to trigger the function"