name: Deploy Ollama Server

on:
  push:
    branches: [ main ]
    paths:
      - 'ollama-server/**'
  workflow_dispatch:

env:
  PROJECT_ID: ai-avatar-451519
  REGION: us-central1
  SERVICE_NAME: ollama-rag
  REPOSITORY: ollama-repo
  IMAGE_NAME: ollama-rag
